# Generated by Django 4.2.2 on 2024-08-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='код верификации email'),
        ),
    ]
