# Generated by Django 4.2.2 on 2024-08-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='datetime',
            field=models.DateTimeField(verbose_name='дата приема'),
        ),
    ]
