# Generated by Django 4.2.2 on 2024-08-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_recording_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='datetime',
            new_name='datetime_rec',
        ),
    ]
